algoritmo "aptoDirigirD"

var

   idade, habilitadoB2, habilitadoC1: inteiro
   infra: caractere

inicio

  Escreval ("Digite a idade do candidato: ")
  Leia(idade)

  Escreval ("Digite em meses quanto tempo possui carteira na categoria B: ")
  Leia (habilitadoB2)
 
  Escreval ("Digite em meses quanto tempo possui carteira na categoria C: ")
  Leia(habilitadoC1)

  Escreval ("Tem infrações nos últimos 12 meses? (N para NÃO/ S para Sim): ")
  Leia (infra)

     Se (idade>= 21) e ((habilitadoB2 >=24) ou (HabilitadoC1>=12)) e (infra= "N")entao
       Escreval ("Apto")
     Senao
       Escreval ("não apto")
     FimSe

fimalgoritmo
