algoritmo "E20"

var

   n: real
   
inicio

      Escreva ("Digite um número: ")
      Leia (n)

      Se (n > 0) entao
         Escreva ("Esse número é positivo")
         
          Senao
            Se (n = 0) entao
               Escreva ("Esse número pe neutro")
              
                 Senao
                  Escreva ("Esse número é negativo")
                
            FimSe
       FimSe
     
fimalgoritmo
