algoritmo "funçõesAritmétricas"
var

 A, B, C, C2, C3, D, D1: real

 
inicio
   A <- abs(-50)
   Escreval (A)
 
   B <- exp(9, 5)
   Escreval (B)
 
   C <- raizq(25)
   Escreval (C)
 
   C2 <- (raizq(90))
   Escreval (C2)
 
   C3 <- Int(RaizQ(90))
   Escreval (C2)
   //não funcionou como deveria
   
   D <- grauprad(90)
   Escreval (D)
   
   D1 <- Sen(grauprad(90))
   Escreval (D1)
   
   
fimalgoritmo
