algoritmo "E10"

var

   nome: caractere
   idade: inteiro
   altura: real

inicio

   Escreval ("Olá, qual é o seu nome? ")
   Leia (nome)
   
   Escreval ("Qual é a sua idade, " , nome, "?")
   leia (idade)

   Escreval ("Entendi! E qual é a sua altura? ")
   leia (altura)
   
   Escreval ("Muito bem! Recapitulando, seu nome é ", nome, ", sua idade é:" , idade, " e você tem " , altura, " de altura" )

fimalgoritmo


//não está lendo numero com virgula
