algoritmo "exemplo37"

var
   n1, n2: inteiro

inicio
      Escreval ("Digite o primeiro número: ")
      Leia (n1)
      
      Escreval ("Digite o segundo número: ")
      Leia (n2)
      
      
      Se (n1 <> n2) entao
          Se (n1 > n2) entao
             Escreval ("O PRIMEIRO número é maior!")
          Senao
             Escreval("O SEGUNDO número é maior!")
          FimSe
       
            Senao
               Escreval ("Números iguais!")
             
      FimSe

fimalgoritmo