//Utilizando estrutura de repetição PARA
//Exibindo a tabuada de 3 de forma decrescente
algoritmo "Ex52"

var
   contador: inteiro


inicio
      Escreval ("-------------------------")
      Escreval ("Inicio do Programa")
      Escreval ("-------------------------")
      
       Para contador de 10 ate 1 passo -1 faca //Vai começar no 10, vai ate o 1 (decrescente), e vai decrementar 1 "passo -1"
          Escreval ("3 x ", contador , " = " , Contador * 3)
      FimPara

fimalgoritmo