//Utilizando estrutura de repetição PARA
//Automatizando geração de matrícula para novos clientes
algoritmo "Ex53"

var
   matricula: inteiro
   nome: caractere

inicio
      Escreval ("-------------------------")
      Escreval ("Inicio do Programa")
      Escreval ("-------------------------")
      
       Para matricula de 2101 ate 2115 faca
          Escreval ("Digite o nome do cliente: ")
          Leia (nome)
          
          Escreval ("A matrícula do(a) cliente ", nome, " é ", matricula)
          Escreval (" ")
      FimPara

fimalgoritmo