algoritmo "Ex59"

var
   resp : inteiro

inicio
      Repita

        Escreval ("-------------------------")
        Escreval (" MENU ")
        Escreval ("-------------------------")
        Escreval ("1 - Cadastrar novo produto")
        Escreval ("2 - Listar Produtos")
        Escreval ("3 - Alterar Produto")
        Escreval ("4 - Excluir Produto")
        Escreval ("5 - Sair")
      
        Escreval ("Digite a opção desejada: ")
        Leia (resp)
        
// (CONDICIONAL PARA MOSTRAR OS ITENS DO MENU), COMO ESTOU FAZENDO APENAS PARA TESTAR A FUNCIONALIDADE DE MENU COM O REPITA, NÃO FAREI O CÓDIGO COMPLETO AGORA
      Ate (resp = 5)
      
fimalgoritmo