algoritmo "Ex60"

var
   age: inteiro

inicio
       Escreval ("-------------------------------------")
       Escreval (" SISTEMA DE AGENDAMENTO DE PROVA CNH ")
       Escreval ("-------------------------------------")
       
       REPITA
         Escreval ("Atenção! todos os canditados devem ser maiores de 18 anos")
         Escreval (" ")
         Escreval ("Digite a idade do canditado: ")
         Leia (age)

        ATE (age >= 18)

fimalgoritmo