//declarando e atribuindo variávies
algoritmo "gerenciamentoLoja07"

var
  calcaJeans: real
  funcionariaDoMes: caractere
  pecasNovas:inteiro
   
inicio

 calcaJeans <- 79.90
 funcionariaDoMes <- "Janaina"
 pecasNovas <- 300
 
 Escreval ("Nessa loja, a funcionária do mês é " , funcionariaDoMes, ", a loja recebeu " ,pecasNovas, " peças novas")
 Escreva(" E as calças jeans estão a partir de R$ ",calcaJeans)


fimalgoritmo