algoritmo "E31"

var

   blusa: caractere

inicio

      Escreval ("Solicite o tamanho da blsa que você deseja(P, M e G): ")
      Leia (blusa)
      
       Escolha (blusa)
        Caso "P"
          Escreva ("P: 0.46 x 0.55")
          
        Caso "M"
          Escreva ("M: 0.51 x 0.56")
          
         Caso "G"
          Escreva ("G: 0.52 x 0.58")
          
         OutroCaso
          Escreva ("Tamanho inválido, por favor escolha P, M ou G")
          
       FimEScolha

fimalgoritmo
