//exemplo prático
Algoritmo "teste_saida"

Var

   a: inteiro
   b: real
   c: caractere
   d: logico

Inicio
   a <- 32
   b <- 2.234
   c <- "Boa Tarde!"
   d <- Verdadeiro

   Escreval("Olá Mundo")
   Escreval //salta uma linha
   Escreval("Bom dia!")
   Escreval 
   Escreval("Boa Noite")

   Escreval(a)
   Escreval
   Escreval(b:15:2)//espaços dado antes de imprimir um número e quantas casas decimais
   Escreval
   Escreval(c)
   Escreval
   Escreval(d)

Fimalgoritmo