algoritmo "E21"

var

   n: inteiro


inicio

      Escreval ("Digite um número de 1 a 7 para saber o dia da semana correspondente: ")
      Leia (n)
      
      Se (n = 1) entao
         Escreva ("O dia é domingo!")
           Senao
            se (n = 2) entao
            Escreva ("O dia é segunda!")
           
             Senao
              se (n = 3) entao
              Escreva ("O dia é terça!")
             
                Senao
                 se (n = 4) entao
                 Escreva ("O dia é quarta!")
                
                  Senao
                   se (n = 5) entao
                   Escreva ("O dia é quinta")
                  
                    Senao
                     se (n = 6) entao
                     Escreva ("O dia é sexta!!")
                    
                      Senao
                       se (n = 7) entao
                       Escreva ("O dia é sábado")
                      
                        Senao
                         Escreva ("Número inválido, por favor escolha um número entre 1 e 7")
        
      
                      FimSe
                   FimSe
                FimSe
             FimSe
          FimSe
        FimSe
      FimSe

fimalgoritmo

//NA MINHA VERSÃO DO VISUALG, NAO TEM COMO COLOCAR "SENAO SE" NA MESMA LINHA
